import { stEl, stUid } from './utils.js';
import BP from './state.js';
import { stLog, stLoadLog } from './log.js';
import { initDragDrop } from './dragdrop.js';
import { initCanvas, destroyCanvas, zoomIn, zoomOut, fitToView } from './canvas.js';
import { showEditor } from './dashboard.js';

const ST_SAMPLE = {
  id: 'sample-morning-briefing',
  name: 'Morning Dev Briefing',
  version: 3,
  status: 'published',
  steps: [
    {
      id: 'fetch_repos', type: 'http', label: 'Fetch trending GitHub repos', collapsed: false,
      config: { method: 'GET', url: 'https://api.github.com/search/repositories?q=stars:>10000&sort=updated&per_page=5', body: '' }
    },
    {
      id: 'sys_info', type: 'code', label: 'Collect system snapshot', collapsed: false,
      config: { command: 'printf "Date: $(date +\\"%A %B %d %Y\\")\\nHost: $(hostname)\\nUptime:$(uptime | sed \'s/.*up//;s/,.*load.*//\')\\nOS: $(uname -srm)"' }
    },
    {
      id: 'ai_summary', type: 'ai', label: 'Generate dev briefing', collapsed: false,
      config: {
        prompt: 'Write a crisp 100-word morning briefing for a developer.\n\nTrending GitHub repos (JSON):\n{{fetch_repos.output}}\n\nSystem info:\n{{sys_info.output}}\n\nCover: #1 trending repo and why it\'s hot, one pattern you notice across the list, and a one-line motivational sign-off.',
        system: 'You are a sharp, no-fluff tech analyst. Be specific about repo names and star counts.'
      }
    },
    {
      id: 'save_briefing', type: 'file', label: 'Save briefing to ~/.buildpipe/briefing.md', collapsed: false,
      config: { operation: 'write', path: '~/.buildpipe/briefing.md', content: '# Dev Briefing — {{date}}\n\n{{ai_summary.output}}\n\n---\n_Generated by buildpipe on {{date}}_' }
    }
  ]
};

let saveTimer = null;
const SAVE_DEBOUNCE = 500;

export function stSave() {
  if (saveTimer) clearTimeout(saveTimer);
  saveTimer = setTimeout(() => doSave(), SAVE_DEBOUNCE);
}

function stSaveImmediate() {
  if (saveTimer) clearTimeout(saveTimer);
  doSave();
}

async function doSave() {
  if (!BP.stairsCurrent) return;
  BP.stairsCurrent.name = stEl('stName').value.trim() || 'Untitled';
  await window.buildpipe.saveStaircase(BP.stairsCurrent);
  stLoadAll();
}

export async function stLoadAll() {
  let all = await window.buildpipe.listStaircases();
  const hasSample = all.find(s => s.id === ST_SAMPLE.id);
  if (!hasSample || (hasSample.version || 0) < ST_SAMPLE.version) {
    await window.buildpipe.saveStaircase(ST_SAMPLE);
    all = await window.buildpipe.listStaircases();
  }
  const list = stEl('stProjectList');
  if (!list) return;
  list.innerHTML = '';
  if (!all.length) {
    list.innerHTML = '<div style="padding:16px 14px;font-size:12px;opacity:0.35;">No pipelines yet</div>';
    return;
  }
  for (const sc of all) {
    const el = document.createElement('div');
    el.className = `st-project-item${sc.status === 'published' ? ' published' : ''}`;
    el.dataset.id = sc.id;
    el.innerHTML = `<span class="st-proj-dot"></span><span class="st-project-name-text">${sc.name || 'Untitled'}</span>`;
    el.addEventListener('click', () => stOpen(sc));
    list.appendChild(el);
  }
  if (all.length === 1 && !BP.stairsCurrent) {
    // Don't auto-open — dashboard is the default view
  }

  BP.updateUndoButtons();
}

export function stOpen(sc) {
  try {
    BP.stairsCurrent = JSON.parse(JSON.stringify(sc));
    BP.stairsOutputs = {};
    stEl('stName').value = sc.name || '';
    const published = sc.status === 'published';
    stEl('stDraftBadge').classList.toggle('hidden', published);
    stEl('stPublishedBadge').classList.toggle('hidden', !published);
    document.querySelectorAll('.st-project-item').forEach(el => {
      el.classList.toggle('active', el.dataset.id === sc.id);
    });
    showEditor();
    stRenderCanvas();
    stLoadLog();
    BP.pushUndo();
    BP.updateUndoButtons();
  } catch (e) {
    stLog(`Error opening pipeline: ${e.message}`, 'log-error');
  }
}

export function stRenderCanvas() {
  const canvas = stEl('stCanvas');
  const nodesEl = stEl('stCanvasNodes');
  const svgEl = stEl('stCanvasSvg');
  const emptyEl = stEl('stEmpty');
  const toolbar = stEl('stMiniToolbar');
  if (!canvas || !nodesEl || !svgEl) return;

  const steps = BP.stairsCurrent?.steps || [];
  const isCanvas = BP.viewMode === 'horizontal';

  destroyCanvas();

  if (isCanvas) {
    canvas.classList.remove('vertical-list');
    nodesEl.classList.remove('vertical-list');
    canvas.style.display = '';
    canvas.style.flexDirection = '';
    canvas.style.overflow = 'hidden';
    nodesEl.style.transform = '';
    nodesEl.style.position = 'absolute';
    nodesEl.style.flex = '';
    nodesEl.style.overflow = '';
    svgEl.style.display = '';
    if (toolbar) toolbar.style.display = 'flex';
    const wrap = canvas.parentElement;
    if (wrap) wrap.style.overflow = 'hidden';
  } else {
    nodesEl.classList.add('vertical-list');
    canvas.style.display = 'flex';
    canvas.style.flexDirection = 'column';
    canvas.style.overflow = '';
    nodesEl.style.transform = 'none';
    nodesEl.style.position = '';
    nodesEl.style.overflow = 'auto';
    nodesEl.style.flex = '1';
    svgEl.style.display = 'none';
    if (toolbar) toolbar.style.display = 'none';
    const wrap = canvas.parentElement;
    if (wrap) wrap.style.overflow = 'visible';
  }

  nodesEl.innerHTML = '';
  svgEl.innerHTML = '';

  if (!steps.length) {
    if (emptyEl) emptyEl.style.display = '';
    if (isCanvas) initCanvas(canvas);
    return;
  }

  if (emptyEl) emptyEl.style.display = 'none';

  if (isCanvas) {
    positionNodes(steps);
    steps.forEach((step, i) => {
      nodesEl.appendChild(stBuildNode(step, i));
    });
    renderConnections(svgEl, steps);
    initNodeDrag(nodesEl);
    initMiniToolbar();
    initCanvas(canvas);
    setTimeout(() => {
      const nodeList = nodesEl.querySelectorAll('.st-node');
      if (nodeList.length) fitToView(nodeList);
    }, 100);
  } else {
    steps.forEach((step, i) => {
      if (i > 0) {
        const conn = document.createElement('div');
        conn.className = 'st-connector';
        conn.innerHTML = '<div class="st-connector-dot"></div>';
        nodesEl.appendChild(conn);
      }
      nodesEl.appendChild(stBuildVerticalCard(step, i));
    });
  }

  for (const [id, res] of Object.entries(BP.stairsOutputs)) {
    stApplyStepOutput(id, res);
  }

  if (!isCanvas) {
    initDragDrop({ onSave: stSave, onRender: stRenderCanvas });
  }
}

const NODE_W = 240;
const NODE_H = 80;
const GAP_X = 100;
const GAP_Y = 80;

function positionNodes(steps) {
  const cols = Math.min(3, steps.length);
  steps.forEach((step, i) => {
    if (!step._x || !step._y) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      step._x = col * (NODE_W + GAP_X);
      step._y = row * (NODE_H + GAP_Y);
    }
  });
}

function stBuildNode(step, index) {
  const el = document.createElement('div');
  el.className = 'st-node';
  el.dataset.id = step.id;
  el.dataset.type = step.type;
  el.style.left = `${step._x || 0}px`;
  el.style.top = `${step._y || 0}px`;

  const typeLabel = { code: 'CODE', ai: 'AI', http: 'HTTP', file: 'FILE', if: 'IF', loop: 'LOOP', notify: 'NOTIFY' }[step.type] || step.type.toUpperCase();
  const iconSvg = {
    code:   '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
    ai:     '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>',
    http:   '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>',
    file:   '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/><polyline points="14 2 14 8 20 8"/><line x1="16" y1="13" x2="8" y2="13"/><line x1="16" y1="17" x2="8" y2="17"/></svg>',
    if:     '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"/></svg>',
    loop:   '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>',
    notify: '<svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>',
  };

  el.innerHTML = `
    <div class="st-node-header">
      <div class="st-node-icon type-${step.type}">${iconSvg[step.type] || ''}</div>
      <div class="st-node-label-wrap">
        <div class="st-node-label">${step.label || 'Untitled step'}</div>
        <div class="st-node-type-tag">${typeLabel}</div>
      </div>
      <span class="st-node-dur" data-dur="${step.id}"></span>
      <span class="st-node-status-dot"></span>
    </div>
    <div class="st-node-body collapsed">${stBuildConfigFields(step)}</div>
    <div class="st-node-actions">
      <button class="st-node-action dup" data-dup="${step.id}" title="Duplicate">⧉</button>
      <button class="st-node-action run" data-rerun="${step.id}" title="Re-run from here">▶</button>
      <button class="st-node-action del" data-del="${step.id}" title="Delete">×</button>
    </div>
    <div class="st-step-output-wrap hidden" data-out-wrap="${step.id}">
      <div class="st-step-output-header">
        <span class="st-step-output-label">Output</span>
        <button class="st-step-output-copy" data-copy="${step.id}">⎘ Copy</button>
      </div>
      <pre class="st-step-output" data-out="${step.id}"></pre>
    </div>
    <div class="st-node-port output" title="Connect to next step"></div>
    ${index > 0 ? '<div class="st-node-port input"></div>' : ''}`;

  el.querySelector('.st-node-header').addEventListener('click', e => {
    if (e.target.closest('button')) return;
    stOpenNodeModal(step);
  });

  el.querySelector(`[data-del="${step.id}"]`).addEventListener('click', e => {
    e.stopPropagation();
    BP.pushUndo();
    BP.stairsCurrent.steps = BP.stairsCurrent.steps.filter(s => s.id !== step.id);
    stSave();
    stRenderCanvas();
  });

  el.querySelector(`[data-dup="${step.id}"]`).addEventListener('click', e => {
    e.stopPropagation();
    stDuplicateStep(step.id);
  });

  el.querySelector(`[data-rerun="${step.id}"]`).addEventListener('click', async e => {
    e.stopPropagation();
    const idx = BP.stairsCurrent.steps.findIndex(s => s.id === step.id);
    const { stRunFrom } = await import('./run.js');
    stRunFrom(idx);
  });

  el.querySelector(`[data-copy="${step.id}"]`)?.addEventListener('click', () => {
    const out = BP.stairsOutputs[step.id];
    if (out) navigator.clipboard.writeText(out.output).catch(() => {});
  });

  el.querySelectorAll('.st-field-input,.st-field-textarea,.st-field-select').forEach(input => {
    input.addEventListener('change', () => stSyncStepConfig(step.id, el));
    input.addEventListener('input', () => stSyncStepConfig(step.id, el));
  });

  return el;
}

function stOpenNodeModal(step) {
  const existing = document.querySelector('.st-node-modal');
  if (existing) existing.remove();

  const typeLabel = { code: 'CODE', ai: 'AI', http: 'HTTP', file: 'FILE', if: 'IF', loop: 'LOOP', notify: 'NOTIFY' }[step.type] || '';
  const iconMap = {
    code:   '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
    ai:     '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>',
    http:   '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/></svg>',
    file:   '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z"/></svg>',
    if:     '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="9 18 15 12 9 6"/></svg>',
    loop:   '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><polyline points="17 1 21 5 17 9"/><path d="M3 11V9a4 4 0 0 1 4-4h14"/><polyline points="7 23 3 19 7 15"/><path d="M21 13v2a4 4 0 0 1-4 4H3"/></svg>',
    notify: '<svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M18 8A6 6 0 0 0 6 8c0 7-3 9-3 9h18s-3-2-3-9"/><path d="M13.73 21a2 2 0 0 1-3.46 0"/></svg>',
  };

  const modal = document.createElement('div');
  modal.className = 'st-node-modal';
  modal.innerHTML = `
    <div class="st-node-modal-backdrop"></div>
    <div class="st-node-modal-card">
      <div class="st-node-modal-hdr">
        <div class="st-node-icon type-${step.type}" style="width:32px;height:32px;border-radius:8px;">${iconMap[step.type] || ''}</div>
        <div style="flex:1;min-width:0;">
          <input class="st-node-modal-title" value="${(step.label || 'Untitled').replace(/"/g, '&quot;')}" data-modal-label="${step.id}" placeholder="Step name" />
          <div style="font-size:10px;opacity:0.4;letter-spacing:0.06em;">${typeLabel}</div>
        </div>
        <button class="st-node-modal-close" title="Close">✕</button>
      </div>
      <div class="st-node-modal-body">
        ${stBuildConfigFields(step)}
      </div>
      <div class="st-node-modal-foot">
        <button class="st-btn st-btn-ai" data-modal-dup="${step.id}">⧉ Duplicate</button>
        <button class="st-btn st-btn-run" data-modal-rerun="${step.id}">▶ Rerun from here</button>
        <button class="st-btn st-btn-del" data-modal-del="${step.id}" style="opacity:1;">Delete</button>
      </div>
      ${BP.stairsOutputs[step.id]?.output ? `
      <div class="st-node-modal-output">
        <div class="st-step-output-header">
          <span class="st-step-output-label">Output</span>
          <button class="st-step-output-copy" data-modal-copy="${step.id}">⎘ Copy</button>
        </div>
        <pre class="st-step-output">${BP.stairsOutputs[step.id].output.slice(0, 4000)}</pre>
      </div>` : ''}
    </div>`;

  document.body.appendChild(modal);

  modal.querySelector('.st-node-modal-backdrop').addEventListener('click', () => modal.remove());
  modal.querySelector('.st-node-modal-close').addEventListener('click', () => modal.remove());

  modal.querySelector(`[data-modal-label="${step.id}"]`).addEventListener('blur', e => {
    step.label = e.target.value.trim() || 'Untitled';
    stSave();
    stRenderCanvas();
  });
  modal.querySelector(`[data-modal-label="${step.id}"]`).addEventListener('keydown', e => {
    if (e.key === 'Enter') { e.preventDefault(); e.target.blur(); }
  });

  modal.querySelector(`[data-modal-dup="${step.id}"]`).addEventListener('click', () => {
    stDuplicateStep(step.id);
    modal.remove();
  });
  modal.querySelector(`[data-modal-rerun="${step.id}"]`).addEventListener('click', async () => {
    modal.remove();
    const idx = BP.stairsCurrent.steps.findIndex(s => s.id === step.id);
    const { stRunFrom } = await import('./run.js');
    stRunFrom(idx);
  });
  modal.querySelector(`[data-modal-del="${step.id}"]`).addEventListener('click', () => {
    BP.pushUndo();
    BP.stairsCurrent.steps = BP.stairsCurrent.steps.filter(s => s.id !== step.id);
    stSave();
    stRenderCanvas();
    modal.remove();
  });
  modal.querySelector(`[data-modal-copy="${step.id}"]`)?.addEventListener('click', () => {
    navigator.clipboard.writeText(BP.stairsOutputs[step.id]?.output || '').catch(() => {});
  });

  modal.querySelectorAll('.st-field-input,.st-field-textarea,.st-field-select').forEach(input => {
    input.addEventListener('change', () => syncModalConfig(step, modal));
    input.addEventListener('input', () => syncModalConfig(step, modal));
  });
}

function syncModalConfig(step, modal) {
  step.config = step.config || {};
  modal.querySelectorAll('[data-key]').forEach(el => {
    step.config[el.dataset.key] = el.value;
  });
  stSave();
}

function renderConnections(svgEl, steps) {
  svgEl.innerHTML = '';
  for (let i = 1; i < steps.length; i++) {
    const from = steps[i - 1];
    const to = steps[i];
    if (!from._x || !to._x) continue;

    const fx = from._x + NODE_W;
    const fy = from._y + NODE_H / 2;
    const tx = to._x;
    const ty = to._y + NODE_H / 2;
    const cx1 = fx + Math.abs(tx - fx) * 0.4;
    const cx2 = tx - Math.abs(tx - fx) * 0.4;
    const path = `M${fx},${fy} C${cx1},${fy} ${cx2},${ty} ${tx},${ty}`;

    const cls = BP.stairsOutputs[from.id]?.ok ? 'st-connection done' : 'st-connection';
    const pathEl = document.createElementNS('http://www.w3.org/2000/svg', 'path');
    pathEl.setAttribute('d', path);
    pathEl.setAttribute('class', cls);
    svgEl.appendChild(pathEl);

    const arrow = document.createElementNS('http://www.w3.org/2000/svg', 'polygon');
    arrow.setAttribute('points', `${tx - 8},${ty - 4} ${tx},${ty} ${tx - 8},${ty + 4}`);
    arrow.setAttribute('class', 'st-connection-arrow');
    svgEl.appendChild(arrow);
  }
}

function initNodeDrag(nodesEl) {
  nodesEl.querySelectorAll('.st-node').forEach(node => {
    let dragging = false, ox = 0, oy = 0;
    node.addEventListener('mousedown', e => {
      if (e.target.closest('button,textarea,input,select,[contenteditable]')) return;
      dragging = true;
      ox = e.clientX - parseInt(node.style.left);
      oy = e.clientY - parseInt(node.style.top);
      node.classList.add('dragging');
      e.preventDefault();
    });
    window.addEventListener('mousemove', e => {
      if (!dragging) return;
      node.style.left = `${e.clientX - ox}px`;
      node.style.top = `${e.clientY - oy}px`;
    });
    window.addEventListener('mouseup', () => {
      if (!dragging) return;
      dragging = false;
      node.classList.remove('dragging');
      const step = BP.stairsCurrent?.steps.find(s => s.id === node.dataset.id);
      if (step) {
        step._x = parseInt(node.style.left);
        step._y = parseInt(node.style.top);
        stSave();
      }
      const svgEl = stEl('stCanvasSvg');
      if (svgEl) renderConnections(svgEl, BP.stairsCurrent?.steps || []);
    });
  });
}

function initMiniToolbar() {
  stEl('stMiniAdd')?.addEventListener('click', () => {
    stEl('stStepTypeMenu').classList.toggle('hidden');
  });

  const zi = stEl('stMiniZoomIn');
  if (zi) { zi.onclick = null; zi.addEventListener('click', () => zoomIn()); }

  const zo = stEl('stMiniZoomOut');
  if (zo) { zo.onclick = null; zo.addEventListener('click', () => zoomOut()); }

  const zf = stEl('stMiniFit');
  if (zf) {
    zf.onclick = null;
    zf.addEventListener('click', () => {
      const nodesEl = stEl('stCanvasNodes');
      const nodeList = nodesEl?.querySelectorAll('.st-node');
      if (nodeList?.length) fitToView(nodeList);
    });
  }
}

export function stBuildVerticalCard(step, index) {
  const el = document.createElement('div');
  el.className = 'st-step';
  el.dataset.id = step.id;
  el.dataset.type = step.type;
  el.dataset.index = String(index);
  el.draggable = true;

  const typeLabel = { code: 'CODE', ai: 'AI', http: 'HTTP', file: 'FILE', if: 'IF', loop: 'LOOP', notify: 'NOTIFY' }[step.type] || step.type.toUpperCase();
  const typeCls = { code: 'st-type-code', ai: 'st-type-ai', http: 'st-type-http', file: 'st-type-file', if: 'st-type-if', loop: 'st-type-loop', notify: 'st-type-notify' }[step.type] || '';

  el.innerHTML = `
    <div class="st-step-header">
      <span class="st-step-grip" title="Drag to reorder">⠿</span>
      <span class="st-step-indicator"></span>
      <span class="st-step-type-badge ${typeCls}">${typeLabel}</span>
      <span class="st-step-label" contenteditable="true" data-id="${step.id}">${step.label || 'Untitled step'}</span>
      <span class="st-step-duration" data-dur="${step.id}"></span>
      <div class="st-step-actions">
        <button class="st-step-action-btn dup" data-dup="${step.id}" title="Duplicate step">⧉</button>
        <button class="st-step-action-btn" data-rerun="${step.id}" title="Re-run from here">↺</button>
        <button class="st-step-action-btn del" data-del="${step.id}" title="Delete step">×</button>
      </div>
    </div>
    <div class="st-step-body" data-body="${step.id}">
      ${stBuildConfigFields(step)}
    </div>
    <div class="st-step-output-wrap hidden" data-out-wrap="${step.id}">
      <div class="st-step-output-header">
        <span class="st-step-output-label">Output</span>
        <button class="st-step-output-copy" data-copy="${step.id}">⎘ Copy</button>
      </div>
      <pre class="st-step-output" data-out="${step.id}"></pre>
    </div>`;

  el.querySelector('[contenteditable]').addEventListener('blur', e => {
    const s = BP.stairsCurrent.steps.find(s => s.id === step.id);
    if (s) { s.label = e.target.textContent.trim(); stSave(); }
  });

  el.querySelector('.st-step-header').addEventListener('click', e => {
    if (e.target.closest('[data-rerun],[data-del],[data-dup],[contenteditable]')) return;
    el.querySelector(`[data-body="${step.id}"]`).classList.toggle('collapsed');
  });

  el.querySelector(`[data-del="${step.id}"]`).addEventListener('click', e => {
    e.stopPropagation();
    BP.pushUndo();
    BP.stairsCurrent.steps = BP.stairsCurrent.steps.filter(s => s.id !== step.id);
    stSave();
    stRenderCanvas();
  });

  el.querySelector(`[data-dup="${step.id}"]`).addEventListener('click', e => {
    e.stopPropagation();
    stDuplicateStep(step.id);
  });

  el.querySelector(`[data-rerun="${step.id}"]`).addEventListener('click', async e => {
    e.stopPropagation();
    const idx = BP.stairsCurrent.steps.findIndex(s => s.id === step.id);
    const { stRunFrom } = await import('./run.js');
    stRunFrom(idx);
  });

  el.querySelector(`[data-copy="${step.id}"]`).addEventListener('click', () => {
    const out = BP.stairsOutputs[step.id];
    if (out) navigator.clipboard.writeText(out.output).catch(() => {});
  });

  el.querySelectorAll('.st-field-input,.st-field-textarea,.st-field-select').forEach(input => {
    input.addEventListener('change', () => stSyncStepConfig(step.id, el));
    input.addEventListener('input', () => stSyncStepConfig(step.id, el));
  });

  return el;
}

function stBuildConfigFields(step) {
  const c = step.config || {};
  const tip = '<span class="st-field-tip">Use <code>{{step_id.output}}</code> to chain steps · <code>{{vars.KEY}}</code> for variables</span>';

  const errorSection = `
    <details class="st-err-section">
      <summary>Error handling</summary>
      <div class="st-field-row" style="margin-top:6px;">
        <div>
          <div class="st-field-label">Retry on error</div>
          <select class="st-field-select" data-key="retry">
            <option value="0"${!c.retry ? ' selected' : ''}>None</option>
            <option value="1"${c.retry == 1 ? ' selected' : ''}>1×</option>
            <option value="2"${c.retry == 2 ? ' selected' : ''}>2×</option>
            <option value="3"${c.retry == 3 ? ' selected' : ''}>3×</option>
          </select>
        </div>
        <div>
          <div class="st-field-label">On failure</div>
          <select class="st-field-select" data-key="continueOnError">
            <option value=""${!c.continueOnError ? ' selected' : ''}>Stop pipeline</option>
            <option value="1"${c.continueOnError === '1' ? ' selected' : ''}>Continue</option>
          </select>
        </div>
      </div>
    </details>`;

  switch (step.type) {
    case 'code':
      return `<div class="st-field-label">Shell command</div>
              <textarea class="st-field-textarea" data-key="command" placeholder="curl https://api.github.com/events | head -20">${c.command || ''}</textarea>${tip}${errorSection}`;

    case 'ai':
      return `<div class="st-field-label">Prompt</div>
              <textarea class="st-field-textarea" data-key="prompt" placeholder="Summarise this: {{prev_step.output}}" style="min-height:96px">${c.prompt || ''}</textarea>${tip}
              <div class="st-field-label" style="margin-top:6px">System prompt (optional)</div>
              <textarea class="st-field-textarea" data-key="system" placeholder="You are a helpful assistant" style="min-height:48px">${c.system || ''}</textarea>${errorSection}`;

    case 'http':
      return `<div class="st-field-row">
                <div><div class="st-field-label">Method</div>
                <select class="st-field-select" data-key="method">
                  ${['GET','POST','PUT','PATCH','DELETE'].map(m => `<option${c.method === m ? ' selected' : ''}>${m}</option>`).join('')}
                </select></div>
                <div><div class="st-field-label">URL</div>
                <input class="st-field-input" data-key="url" value="${c.url || ''}" placeholder="https://api.example.com/data" /></div>
              </div>
              <div class="st-field-label" style="margin-top:6px">Body JSON (optional)</div>
              <textarea class="st-field-textarea" data-key="body" placeholder='{"key":"value"}' style="min-height:56px">${c.body || ''}</textarea>${tip}${errorSection}`;

    case 'file':
      return `<div class="st-field-row">
                <div><div class="st-field-label">Operation</div>
                <select class="st-field-select" data-key="operation">
                  <option${c.operation === 'read' ? ' selected' : ''}>read</option>
                  <option${c.operation === 'write' ? ' selected' : ''}>write</option>
                  <option${c.operation === 'append' ? ' selected' : ''}>append</option>
                </select></div>
                <div><div class="st-field-label">Path</div>
                <input class="st-field-input" data-key="path" value="${c.path || ''}" placeholder="~/.buildpipe/output.md" /></div>
              </div>
              <div class="st-field-label" style="margin-top:6px">Content (write/append only)</div>
              <textarea class="st-field-textarea" data-key="content" placeholder="{{prev_step.output}}">${c.content || ''}</textarea>${tip}${errorSection}`;

    case 'if':
      return `<div class="st-field-label">Value to check</div>
              <input class="st-field-input" data-key="value" value="${c.value || ''}" placeholder="{{prev_step.output}}" />${tip}
              <div class="st-field-row" style="margin-top:6px;">
                <div>
                  <div class="st-field-label">Operator</div>
                  <select class="st-field-select" data-key="operator">
                    <option value="contains"${(c.operator||'contains')==='contains'?' selected':''}>contains</option>
                    <option value="not-contains"${c.operator==='not-contains'?' selected':''}>does not contain</option>
                    <option value="equals"${c.operator==='equals'?' selected':''}>equals</option>
                    <option value="not-equals"${c.operator==='not-equals'?' selected':''}>not equals</option>
                    <option value="not-empty"${c.operator==='not-empty'?' selected':''}>is not empty</option>
                    <option value="empty"${c.operator==='empty'?' selected':''}>is empty</option>
                  </select>
                </div>
                <div>
                  <div class="st-field-label">Compare to</div>
                  <input class="st-field-input" data-key="against" value="${c.against || ''}" placeholder="error" />
                </div>
              </div>
              <div class="st-field-label" style="margin-top:6px;">If false</div>
              <select class="st-field-select" data-key="on_false">
                <option value="stop"${(c.on_false||'stop')==='stop'?' selected':''}>Stop pipeline</option>
                <option value="continue"${c.on_false==='continue'?' selected':''}>Continue anyway</option>
              </select>`;

    case 'loop':
      return `<div class="st-field-label">Items (JSON array or newline-separated)</div>
              <input class="st-field-input" data-key="items" value="${c.items || ''}" placeholder="{{prev_step.output}}" />${tip}
              <div class="st-field-row" style="margin-top:6px;">
                <div>
                  <div class="st-field-label">Step type</div>
                  <select class="st-field-select" data-key="step_type">
                    <option value="code"${(c.step_type||'code')==='code'?' selected':''}>Code</option>
                    <option value="ai"${c.step_type==='ai'?' selected':''}>AI</option>
                    <option value="http"${c.step_type==='http'?' selected':''}>HTTP</option>
                  </select>
                </div>
                <div>
                  <div class="st-field-label">Max items</div>
                  <input class="st-field-input" data-key="max_items" type="number" value="${c.max_items || 10}" style="width:80px;" />
                </div>
              </div>
              <div class="st-field-label" style="margin-top:6px;">Command / Prompt / URL <span style="opacity:.4;font-size:10px;">(use {{_item.output}} for current item)</span></div>
              <textarea class="st-field-textarea" data-key="command" placeholder="echo '{{_item.output}}'">${c.command || c.prompt || c.url || ''}</textarea>
              <div class="st-field-label" style="margin-top:6px;">On item error</div>
              <select class="st-field-select" data-key="continue_on_error">
                <option value=""${!c.continue_on_error?' selected':''}>Stop loop</option>
                <option value="1"${c.continue_on_error==='1'?' selected':''}>Continue</option>
              </select>`;

    case 'notify':
      return `<div class="st-field-label">Title</div>
              <input class="st-field-input" data-key="title" value="${c.title || ''}" placeholder="Pipeline completed" />
              <div class="st-field-label" style="margin-top:6px;">Message</div>
              <textarea class="st-field-textarea" data-key="message" placeholder="{{prev_step.output}}">${c.message || ''}</textarea>${tip}
              <div class="st-field-label" style="margin-top:6px;">Channel</div>
              <select class="st-field-select" data-key="channel">
                <option value="system"${(c.channel||'system')==='system'?' selected':''}>System notification</option>
                <option value="webhook"${c.channel==='webhook'?' selected':''}>Webhook (POST)</option>
              </select>
              ${c.channel === 'webhook' ? `<div class="st-field-label" style="margin-top:6px;">Webhook URL</div>
              <input class="st-field-input" data-key="webhook_url" value="${c.webhook_url || ''}" placeholder="https://hooks.slack.com/..." />` : ''}`;

    default:
      return '';
  }
}

function stSyncStepConfig(stepId, cardEl) {
  const step = BP.stairsCurrent?.steps.find(s => s.id === stepId);
  if (!step) return;
  step.config = step.config || {};
  cardEl.querySelectorAll('[data-key]').forEach(input => {
    step.config[input.dataset.key] = input.value;
  });
  stSave();
}

export function stApplyStepOutput(stepId, res) {
  const card = document.querySelector(`.st-node[data-id="${stepId}"]`) || document.querySelector(`.st-step[data-id="${stepId}"]`);
  if (!card) return;
  card.classList.remove('st-running', 'st-done', 'st-error');
  card.classList.add(res.ok ? 'st-done' : 'st-error');
  const outWrap = card.querySelector(`[data-out-wrap="${stepId}"]`);
  const outEl = card.querySelector(`[data-out="${stepId}"]`);
  if (outWrap && outEl) {
    outWrap.classList.remove('hidden');
    outEl.textContent = res.output?.slice(0, 4000) || '(no output)';
    outEl.className = `st-step-output${res.ok ? '' : ' error'}`;
  }
  const durEl = card.querySelector(`[data-dur="${stepId}"]`);
  if (durEl) {
    const idx = BP.stairsCurrent?.steps.findIndex(s => s.id === stepId);
    // duration is set by run.js
  }
}

export function stAddStep(type) {
  if (!BP.stairsCurrent) {
    BP.stairsCurrent = {
      id: stUid(), name: stEl('stName').value.trim() || 'Untitled',
      steps: [], status: 'draft', created: new Date().toISOString()
    };
  }
  BP.pushUndo();
  const defaults = {
    code:   { command: '' },
    ai:     { prompt: '', system: '' },
    http:   { url: '', method: 'GET', body: '' },
    file:   { operation: 'read', path: '', content: '' },
    if:     { value: '', operator: 'contains', against: '', on_false: 'stop' },
    loop:   { items: '', step_type: 'code', command: '', max_items: 10, continue_on_error: '' },
    notify: { title: 'Pipeline completed', message: '', channel: 'system' },
  };
  BP.stairsCurrent.steps.push({
    id: stUid(), type, label: `${type.charAt(0).toUpperCase() + type.slice(1)} step`,
    config: defaults[type] || {}
  });
  stSaveImmediate();
  stRenderCanvas();
  const canvas = stEl('stCanvas');
  if (canvas) setTimeout(() => canvas.scrollTop = canvas.scrollHeight, 50);
}

export function stDuplicateStep(stepId) {
  const idx = BP.stairsCurrent.steps.findIndex(s => s.id === stepId);
  if (idx === -1) return;
  BP.pushUndo();
  const original = BP.stairsCurrent.steps[idx];
  const clone = JSON.parse(JSON.stringify(original));
  clone.id = stUid();
  clone.label = (clone.label || 'Step') + ' (copy)';
  BP.stairsCurrent.steps.splice(idx + 1, 0, clone);
  stSaveImmediate();
  stRenderCanvas();
}


